# Basic
name:               "Soreine - Blog"
description:        "A blog"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "soreine.github.io"
author:             "Soreine"

# serve
baseurl:            "/blog"

# URL
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

exlude:
  - .working/
# Disqus
enable_disqus: true
disqus_short_name: soreinegithubioblog

gems:
  - jekyll-seo-tag